// <auto-generated />
using System;
using GymSysM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GymSysM.Migrations
{
    [DbContext(typeof(BdGymContext))]
    [Migration("20220216214609_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GymSysM.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idActividad")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdActividad");

                    b.ToTable("Actividad");
                });

            modelBuilder.Entity("GymSysM.Models.CategoriaEmpleado", b =>
                {
                    b.Property<int>("IdCategoriaEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCategoriaEmpleado")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnName("salarioBase")
                        .HasColumnType("money");

                    b.Property<decimal>("SalarioHora")
                        .HasColumnName("salarioHora")
                        .HasColumnType("money");

                    b.HasKey("IdCategoriaEmpleado")
                        .HasName("PK_CategoriaEmpleado_1");

                    b.ToTable("CategoriaEmpleado");
                });

            modelBuilder.Entity("GymSysM.Models.Clase", b =>
                {
                    b.Property<int>("IdClase")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idClase")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnName("capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Dia")
                        .IsRequired()
                        .HasColumnName("dia")
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true)
                        .HasMaxLength(10);

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnName("horaFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnName("horaInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdActividad")
                        .HasColumnName("idActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnName("idEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnName("idSala")
                        .HasColumnType("int");

                    b.HasKey("IdClase");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdSala");

                    b.ToTable("Clase");
                });

            modelBuilder.Entity("GymSysM.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idCliente")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnName("apellidos")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("CantSesionesUva")
                        .HasColumnName("cantSesionesUVA")
                        .HasColumnType("int");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnName("correo")
                        .HasColumnType("xml");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("direccion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnName("DNI")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("estado")
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnName("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRenovacion")
                        .HasColumnName("fechaRenovacion")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSubscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fechaSubscripcion")
                        .HasColumnType("date")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("IdSubscripcion")
                        .HasColumnName("idSubscripcion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("SesionesUVAdisp")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("sesionesUVAdisp")
                        .HasColumnType("int")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnName("telefono")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdCliente");

                    b.HasIndex("IdSubscripcion");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GymSysM.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idEmpleado")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnName("apellidos")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Correo")
                        .HasColumnName("correo")
                        .HasColumnType("xml");

                    b.Property<string>("CuentaIban")
                        .IsRequired()
                        .HasColumnName("cuentaIBAN")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("direccion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnName("DNI")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnName("fechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCategoriaEmpleado")
                        .HasColumnName("idCategoriaEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("NSeguroSocial")
                        .IsRequired()
                        .HasColumnName("nSeguroSocial")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Telefono")
                        .HasColumnName("telefono")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdCategoriaEmpleado");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("GymSysM.Models.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idMatricula")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("fechaHora")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("IdClase")
                        .HasColumnName("idClase")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnName("idCliente")
                        .HasColumnType("int");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdClase");

                    b.HasIndex("IdCliente");

                    b.ToTable("Matricula");
                });

            modelBuilder.Entity("GymSysM.Models.Planilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPlanilla")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Ccss")
                        .HasColumnName("CCSS")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<int>("HorasTrabajadas")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("horasTrabajadas")
                        .HasColumnType("int")
                        .HasDefaultValueSql("((8))");

                    b.Property<int>("IdEmpleado")
                        .HasColumnName("idEmpleado")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalarioBruto")
                        .HasColumnName("salarioBruto")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("SalarioHora")
                        .HasColumnName("salarioHora")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal?>("SalarioNeto")
                        .HasColumnName("salarioNeto")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Planilla");
                });

            modelBuilder.Entity("GymSysM.Models.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idSala")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacidad")
                        .HasColumnName("capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdSala");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("GymSysM.Models.SesionUva", b =>
                {
                    b.Property<int>("IdSesionUva")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idSesionUVA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Duracion")
                        .HasColumnName("duracion")
                        .HasColumnType("time");

                    b.Property<DateTime>("Fecha")
                        .HasColumnName("fecha")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnName("horaInicio")
                        .HasColumnType("time");

                    b.Property<int>("IdCliente")
                        .HasColumnName("idCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnName("idEmpleado")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarifa")
                        .HasColumnName("tarifa")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdSesionUva");

                    b.HasIndex("IdCliente");

                    b.ToTable("SesionUVA");
                });

            modelBuilder.Entity("GymSysM.Models.Subscripcion", b =>
                {
                    b.Property<int>("IdSubscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idSubscripcion")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadSesionesUva")
                        .HasColumnName("cantidadSesionesUVA")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Meses")
                        .HasColumnName("meses")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("nombre")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Tarifa")
                        .HasColumnName("tarifa")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("IdSubscripcion");

                    b.ToTable("Subscripcion");
                });

            modelBuilder.Entity("GymSysM.Models.Clase", b =>
                {
                    b.HasOne("GymSysM.Models.Actividad", "IdActividadNavigation")
                        .WithMany("Clase")
                        .HasForeignKey("IdActividad")
                        .HasConstraintName("FK_Clase_Actividad")
                        .IsRequired();

                    b.HasOne("GymSysM.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Clase")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_Clase_Empleado")
                        .IsRequired();

                    b.HasOne("GymSysM.Models.Sala", "IdSalaNavigation")
                        .WithMany("Clase")
                        .HasForeignKey("IdSala")
                        .HasConstraintName("FK_Clase_Sala")
                        .IsRequired();
                });

            modelBuilder.Entity("GymSysM.Models.Cliente", b =>
                {
                    b.HasOne("GymSysM.Models.Subscripcion", "IdSubscripcionNavigation")
                        .WithMany("Cliente")
                        .HasForeignKey("IdSubscripcion")
                        .HasConstraintName("FK_Cliente_Subscripcion")
                        .IsRequired();
                });

            modelBuilder.Entity("GymSysM.Models.Empleado", b =>
                {
                    b.HasOne("GymSysM.Models.CategoriaEmpleado", "IdCategoriaEmpleadoNavigation")
                        .WithMany("Empleado")
                        .HasForeignKey("IdCategoriaEmpleado")
                        .HasConstraintName("FK_Empleado_CategoriaEmpleado")
                        .IsRequired();
                });

            modelBuilder.Entity("GymSysM.Models.Matricula", b =>
                {
                    b.HasOne("GymSysM.Models.Clase", "IdClaseNavigation")
                        .WithMany("Matricula")
                        .HasForeignKey("IdClase")
                        .HasConstraintName("FK_Matricula_Clase")
                        .IsRequired();

                    b.HasOne("GymSysM.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Matricula")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_Matricula_Cliente")
                        .IsRequired();
                });

            modelBuilder.Entity("GymSysM.Models.Planilla", b =>
                {
                    b.HasOne("GymSysM.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Planilla")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_Planilla_Empleado")
                        .IsRequired();
                });

            modelBuilder.Entity("GymSysM.Models.SesionUva", b =>
                {
                    b.HasOne("GymSysM.Models.Cliente", "IdClienteNavigation")
                        .WithMany("SesionUva")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_SesionUVA_Cliente")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
